### ISSUE TITLE
SRC and ESRC cannot get output result

### ISSUE THREAD

**Issue by YMCLEARNER** [Js2Hou/Euler-Ridge-Regression#1]
#### Image below shows that CRC and ECRC run properly but SRC keeps running:
![1](https://user-images.githubusercontent.com/98655066/151667588-9c186a87-fb07-4f1a-9df6-490e8c5f8ee2.png)
#### Image below shows that LRC, RRC and ERRC run properly but ESRC keeps running:
![image](https://user-images.githubusercontent.com/98655066/151667765-5c04fe7b-c506-4db9-89e6-e4b656d8d331.png)

#### Here is attached with my ipynb file which try to run all the algorithms:
[Performance Evaluation.zip](https://github.com/Js2Hou/Subspace-Regression-based-Face-Recognition/files/7964053/Performance.Evaluation.zip)

**Comment by Js2Hou** [comment]
Wait a while. The SRC-based approach has no closed solution, which is solved by iteration. Therefore, it takes a long time.

**Comment by YMCLEARNER** [comment]
> Wait a while. The SRC-based approach has no closed solution, which is solved by iteration. Therefore, it takes a long time.

### Thanks for responding me! But I tried to let it run for more than 6 hours, it still won't get any output result (accuracy)... By the way, I tried to remove the # of print(prob.status) for checking that whether the SRC algorithm is running or not however it keeps output "optimal" and also won't get any accuracy result... May I know that how long that you wait for getting the accuracy of this SRC-based algorithm?

#### Image below shows that the time that I start for running the SRC algorithm:
![1](https://user-images.githubusercontent.com/98655066/151712637-02d143ea-b514-4e0a-97b7-d4b90d901531.png)

#### Image below shows that the time that I run the SRC algorithm for more than 6 hours (it still don't get any accuracy result yet):
![image](https://user-images.githubusercontent.com/98655066/151713464-1c897aae-ab1f-4991-9783-b4b8aa100d4f.png)
